[workspace]
resolver = "2"
members = [
    "dace",
    "dace_tests",
    "stack_alg_sim",
    "hist",
    "tracer",
    "list_serializable",
    "stack_test_cases",
    "benches/lruvec_bench",
    "benches/stack_alg_sim_bench",
    "polybenchrun",
    "aws_utilities"
]